
# Taller 1
## Punto 1
Escriba un programa que simule el juego Piedra, papel, tijera para dos jugadores (Inés y Juan).

Las reglas del juego son las siguientes:

1.) Simultáneamente, los dos jugadores muestran una mano en tres posibles posiciones:
  * Piedra: se muestra el puño cerrado.
  * Papel: se muestra la palma de la mano.
  * Tijera: se muestra la palma de la mano con los dedos separados en dos grupos.

2.) El jugador que ha sacado Piedra gana al jugador que ha sacado Tijera.

3.) El jugador que ha sacado Tijera gana al jugador que ha sacado Papel.

4.) El jugador que ha sacado Papel gana al jugador que ha sacado Piedra.

In [ ]:
# importamos la librería Random, y le damos como nombre ran dentro del programa
import random as ran

In [ ]:
Ines = ran.choice(["Piedra","Papel","Tijera"])
print(f'la jugadora Ines sacó {Ines}')
Juan = ran.choice(["Piedra","Papel","Tijera"])
print(f'El jugador Juan sacó {Juan}')
if Juan == Ines:
    print("Empate")
else:
    if Juan == "Papel" and Ines == "Piedra":
      print("El ganador es Juan")
    else:
        if Juan == "Papel" and Ines == "Tijera":
           print("la ganadora es Ines")
        else:
            if Juan == "Piedra" and Ines == "Papel":
                print("la ganadora es Ines")
            else:
                if Juan == "Piedra" and Ines == "Tijera":
                    print("El ganador es Juan")
                else:
                    if Juan == "Tijera" and Ines == "Papel":
                        print("El ganador es Juan")
                    else:
                        if Juan == "Tijera" and Ines == "Piedra":
                            print("La ganadora es Ines")



la jugadora Ines sacó Tijera
El jugador Juan sacó Tijera
Empate


# Punto 2
Generar una matriz de 7 por 9. Las primeras 3 columnas de la matriz tienen que tener el valor 0. 

La cuarta columna debe tener el valor 0.5, excepto por el último valor de esa columna, que tiene que ser 0.7.

Las otras tres columnas deben tener el valor 1.

* Luego imprimir la matriz
* Imprimir también el promedio de la ultima fila.

In [ ]:
# importamos la librería numpy, y le damos como nombre np dentro del programa
import numpy as np

Profe hice dos versiones de este punto, ya que por el enunciado entiendo que son 7 filas y 9 columnas, sin embargo por las especificaciones pareciera al contrario.

In [ ]:
#Se inicia la creación de matriz
dimensiones=(7,9)
m = np.zeros(dimensiones)

m[:,3]=m[:,3]+0.5
m[6,3]=m[6,3]+0.2

m[:,4]=m[:,4]+1
m[:,5]=m[:,5]+1
m[:,6]=m[:,6]+1
print(m)

promedio= np.average(m[6,:])
print(promedio)

[[0.  0.  0.  0.5 1.  1.  1.  0.  0. ]
 [0.  0.  0.  0.5 1.  1.  1.  0.  0. ]
 [0.  0.  0.  0.5 1.  1.  1.  0.  0. ]
 [0.  0.  0.  0.5 1.  1.  1.  0.  0. ]
 [0.  0.  0.  0.5 1.  1.  1.  0.  0. ]
 [0.  0.  0.  0.5 1.  1.  1.  0.  0. ]
 [0.  0.  0.  0.7 1.  1.  1.  0.  0. ]]
0.41111111111111115


**Segunda** **opción**

In [ ]:
#Se inicia la creación de matriz
dimensiones=(9,7)
m = np.zeros(dimensiones)

m[:,3]=m[:,3]+0.5
m[8,3]=m[8,3]+0.2

m[:,4]=m[:,4]+1
m[:,5]=m[:,5]+1
m[:,6]=m[:,6]+1
print(m)

promedio= np.average(m[8,:])
print(promedio)

[[0.  0.  0.  0.5 1.  1.  1. ]
 [0.  0.  0.  0.5 1.  1.  1. ]
 [0.  0.  0.  0.5 1.  1.  1. ]
 [0.  0.  0.  0.5 1.  1.  1. ]
 [0.  0.  0.  0.5 1.  1.  1. ]
 [0.  0.  0.  0.5 1.  1.  1. ]
 [0.  0.  0.  0.5 1.  1.  1. ]
 [0.  0.  0.  0.5 1.  1.  1. ]
 [0.  0.  0.  0.7 1.  1.  1. ]]
0.5285714285714286


# Punto 3
La siguiente linea crea una matriz aleatoria de 5 por 5 con valores entre 0 y 1

```
matriz_aleatoria=np.random.rand(5,5) 
print(matriz_aleatoria)
```

Imprimir las posiciones (Fila y columna) de los elementos de la matriz que son mayores que 0.5


In [ ]:
matriz_aleatoria=np.random.rand(5,5) 
print(matriz_aleatoria)


[[0.76402546 0.03247289 0.73331157 0.22607407 0.69935162]
 [0.81750949 0.85495376 0.82772199 0.99515839 0.06387794]
 [0.74326614 0.82232054 0.34120405 0.50259664 0.22268001]
 [0.82256938 0.75609366 0.90250734 0.7356281  0.903153  ]
 [0.3680827  0.46806126 0.44571696 0.65456614 0.82094761]]


In [ ]:
np.where(matriz_aleatoria > 0.5)

(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4]),
 array([0, 2, 4, 0, 1, 2, 3, 0, 1, 3, 0, 1, 2, 3, 4, 3, 4]))